name:                sklearn
version:             0.1.0.0
github:              "githubuser/sklearn"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

include-dirs: cbits
c-sources: cbits/*.c
install-includes: glue.h

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/sklearn#readme>

default-extensions:
- BangPatterns
- MultiParamTypeClasses
- ScopedTypeVariables
- OverloadedStrings
- KindSignatures
- DataKinds
- PolyKinds
- FlexibleInstances
- DeriveGeneric
- RecordWildCards
- DuplicateRecordFields
- FlexibleContexts
- DeriveFunctor
- TypeOperators
- GeneralizedNewtypeDeriving
- TypeFamilies
- TupleSections
- NamedFieldPuns
- RankNTypes
- TypeApplications
- DefaultSignatures
- StandaloneDeriving
- LambdaCase

build-tools:
- c2hs

dependencies:
- base >= 4.7 && < 5
- text
- containers
- unordered-containers
- bytestring
- aeson
- async
  # - unix
- process
- filepath
- directory
- lens
- lens-aeson
- yaml
- time
- repa
- repa-algorithms
- vector
- inline-c
- exceptions
- template-haskell
- random
- mtl

data-files: pybits/**/*.py

library:
  source-dirs: src
  pkg-config-dependencies: python3, glib-2.0
  ghc-options: 
    - -g

executables:
  sklearn-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: 
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N1
      - -g
    dependencies:
    - sklearn

tests:
  sklearn-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sklearn
